var risks = [
  { value: "totrisk",
    text: "Total Cancer Risk (per million)"},
  { value: "risk1",
    text: "PT-StationaryPoint Cancer Risk (per million)"},
  { value: "risk2",
    text: "OR-LightDuty-OffNetwork-Gas Cancer Risk (per million)"},
  { value: "risk3",
    text: "OR-LightDuty-OffNetwork-Diesel Cancer Risk (per million)"},
  { value: "risk4",
    text: "OR-HeavyDuty-OffNetwork-Gas Cancer Risk (per million)"},
  { value: "risk5",
    text: "OR-HeavyDuty-OffNetwork-Diesel Cancer Risk (per million)"},
  { value: "risk6",
    text: "OR-LightDuty-OnNetwork-Gas Cancer Risk (per million)"},
  { value: "risk7",
    text: "OR-LightDuty-OnNetwork-Diesel Cancer Risk (per million)"},
  { value: "risk8",
    text: "OR-HeavyDuty-OnNetwork-Gas Cancer Risk (per million)"},
  { value: "risk9",
    text: "OR-HeavyDuty-OnNetwork-Diesel Cancer Risk (per million)"},
  { value: "risk10",
    text: "OR-Refueling Cancer Risk (per million)"},
  { value: "risk11",
    text: "OR-HeavyDuty-Hoteling Cancer Risk (per million)"},
  { value: "risk12",
    text: "NR-Recreational-inc-PleasureCraft Cancer Risk (per million)"},
  { value: "risk13",
    text: "NR-Construction Cancer Risk (per million)"},
  { value: "risk14",
    text: "NR-CommercialLawnGarden Cancer Risk (per million)"},
  { value: "risk15",
    text: "NR-ResidentialLawnGarden Cancer Risk (per million)"},
  { value: "risk16",
    text: "NR-Agriculture Cancer Risk (per million)"},
  { value: "risk17",
    text: "NR-CommercialEquipment Cancer Risk (per million)"},
  { value: "risk18",
    text: "NR-AllOther Cancer Risk (per million)"},
  { value: "risk19",
    text: "NR-CMV_C1C2 Cancer Risk (per million)"},
  { value: "risk20",
    text: "NR-CMV_C3 Cancer Risk (per million)"},
  { value: "risk21",
    text: "NR-CMV_C1C2C3_underway Cancer Risk (per million)"},
  { value: "risk22",
    text: "NR-Locomotives Cancer Risk (per million)"},
  { value: "risk23",
    text: "NR-Point-Airports Cancer Risk (per million)"},
  { value: "risk24",
    text: "NR- Point-Railyards Cancer Risk (per million)"},
  { value: "risk25",
    text: "NP-industrial Cancer Risk (per million)"},
  { value: "risk26",
    text: "NP-CommercialCooking Cancer Risk (per million)"},
  { value: "risk27",
    text: "NP-OilGas Cancer Risk (per million)"},
  { value: "risk28",
    text: "NP-SolventsCoatings Cancer Risk (per million)"},
  { value: "risk29",
    text: "NP-StorageTransfer_BulkTerminals_GasStage1 Cancer Risk"},
  { value: "risk30",
    text: "NP-MiscellaneousNonindustrial Cancer Risk (per million)"},
  { value: "risk31",
    text: "NP-FuelCombustion_not_RWC Cancer Risk (per million)"},
  { value: "risk32",
    text: "NP-ResidentialWoodCombustionRWC Cancer Risk (per million)"},
  { value: "risk33",
    text: "NP-WasteDisposal Cancer Risk (per million)"},
  { value: "risk34",
    text: "NP-AgricultureLivestock Cancer Risk (per million)"},
  { value: "risk35",
    text: "FIRE Cancer Risk (per million)"},
  { value: "risk36",
    text: "BIOGENICS Cancer Risk (per million)"},
  { value: "risk37",
    text: "SECONDARY Cancer Risk (per million)"},
  { value: "risk38",
    text: "BACKGROUND Cancer Risk (per million)"},
  { value: "hi_resp",
    text: "Total Respiratory HI"},
  { value: "hi_neur",
    text: "Total Neurological HI"},
  { value: "hi_live",
    text: "Total Liver HI"},
  { value: "hi_deve",
    text: "Total Developmental HI"},
  { value: "hi_repr",
    text: "Total Reproductive HI"},
  { value: "hi_kidn",
    text: "Total Kidney HI"},
  { value: "hi_ocul",
    text: "Total Ocular HI"},
  { value: "hi_endo",
    text: "Total Endocrine HI"},
  { value: "hi_hema",
    text: "Total Hematological HI"},
  { value: "hi_immu",
    text: "Total Immunological HI"},
  { value: "hi_skel",
    text: "Total Skeletal HI"},
  { value: "hi_sple",
    text: "Total Spleen HI"},
  { value: "hi_thyr",
    text: "Total Thyroid HI"},
  { value: "hi_whol",
    text: "Total Wholebody HI"}
]
